### ISSUE TITLE
Text composer is cleared when leaving timeline screen

### ISSUE THREAD

**Issue by noantiq** [element-hq/element-x-android#2898] opened 2024-05-22 18:02 UTC
### Steps to reproduce

1. Open a room
2. type a message but don't send it yet
3. leave the screen (eg. by navigating back to the room list, opening the room's description by clicking it's title or simply sending a picture)

#### What did you expect?
My message draft is still there and I can continue writing my message or send it.
#### What happened instead?
The composer is cleared, my message draft is gone.

With a version preceding the introduction of the new plain text editor (yesterday's nightly for example), the composer wasn't cleared when opening the room description or sending a picture. It was cleared when navigating back to the room list in previous versions as well, which was annoying enough.

### Application version and app store

Today's nightly (2024-05-22)

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by frebib** [comment] 2024-05-22 19:29
Duplicate of #2869

**Closed** 2024-05-23 12:59 UTC
Labels: S-Minor, T-Defect, O-Frequent, A-Composer
