### ISSUE TITLE
old version of f-droid, play store nagging 

### ISSUE THREAD

**Issue by cptechnik** [element-hq/element-x-android#3404] opened 2024-09-05 13:27 UTC
### Your use case

English is my foreign language, German my native...

#### What would you like to do?
Not be nagged 
Having the newest version on f-droid (047)
Google playstore nags with problem by installing new version (050)

#### Why would you like to do it?
Really? ... Because of the relative humidity of the sand on the moon!  

#### How would you like to achieve it?
By click 

### Have you considered any alternatives?

I don't want Google playstore...

I could remove and install by Google playstore,... I don't want...

Is there a downloadable binary?

### Additional context

This form: "Are you willing to provide a PR?"
I don't know what is PR... It's the abbreviation of my uncle Paul Radke, ... But... And the star is not linking...

### Are you willing to provide a PR?

No

**Comment by genofire** [comment] 2024-09-12 15:52
This might be a duplicate of https://github.com/element-hq/element-x-android/issues/3420.

**Comment by licaon-kter** [comment] 2024-09-13 13:56
> Google playstore nags with problem by installing new version (050)

picture?

**Comment by spaetz** [comment] 2024-11-04 14:04
Given f-droid is currently on 0.7.2 and up to date, this issue should be closed IMO.

**Closed** 2024-11-05 08:05 UTC
Labels: T-Enhancement
