### ISSUE TITLE
Switch to using a Universal Link for the OIDC callback.

### ISSUE THREAD

**Issue by pixlwave** [element-hq/element-x-android#1282] opened 2023-09-12 09:54 UTC
Now that https://github.com/matrix-org/matrix-rust-sdk/pull/2503 has been merged, we can easily switch from using `io.element:/callback` for the OIDC callback to a Universal Link (maybe that's an iOSism naming wise). We need to use the same domain as the `client_uri` in the `OidcConfiguration` so on iOS we're looking to use `https://element.io/mobile/oidc/bundleidsuffix` as seen in this draft PR https://github.com/vector-im/element-x-ios/pull/1681 (although its not fully working for us yet).

The `bundleidsuffix` is a workaround for iOS not having any control over *which* app opens if multiple apps support the same universal link so might not be necessary on Android, but for visibility it means the following:

`https://element.io/mobile/oidc/elementx` for App Store and TestFlight releases.
`https://element.io/mobile/oidc/nightly` for the Nightly TestFlight release.
`https://element.io/mobile/oidc/pr` for Diawi PR builds.

**Comment by pixlwave** [comment] 2023-09-26 10:52
Small note: On iOS we're switching this to use `https://mobile.element.io/oidc/bundleidsuffix` as there were some reliability issues using the `element.io` domain directly. I don't think there is any particular reason to align on this other than consistency between platforms, so sharing here for you to make the choice :)

**Comment by bmarty** [comment] 2023-10-04 13:03
The problem when using `https` scheme on EXA is that the application does not intercept it, so the URL is opened in the Web browser, which is not fine. Using a custom scheme work, but the whole url is displayed on the web page (instead of just the domain). This is a bit nicer than the previous `io.element:/callback` though:

<img width="331" alt="image" src="https://github.com/vector-im/element-x-android/assets/3940906/1c69e1ef-2458-4c2c-a13f-49168e565faf">

@pixlwave did you have the same issue on iOS?

**Comment by sandhose** [comment] 2023-10-04 14:09
So first, on the native callback, you should keep using something like `io.element:/`, because the reverse DNS notation for the scheme is ~enforced the [OAuth 2.0 for Native Apps](https://datatracker.ietf.org/doc/html/rfc8252#section-7.1). We actually enforce that in MAS, and I don't know why it let you go through on element.io? Maybe that policy is temporarily disabled there.

What I don't understand, is that looking at the Android docs, looks like this is supposed to be supported [since API 23](https://developer.android.com/training/app-links/index.html#android-app-links)? So I don't know what's up with that. Is this something you can reliably reproduce? Maybe it has to do with the HTTP code we're using for redirections? I can explore tweaking that if that's useful.

Maybe we could register both redirect URIs during client registration, and use the best one by resolving the activity and make sure we're the one handling it, by checking which activity would be launched?

Something like:

```java
getPackageManager().resovleActivity(
    new Intent(Intent.ACTION_VIEW, "https://mobile.element.io/oidc/"),
    PackageManager.MATCH_DEFAULT_ONLY)
```

and matching on the package name?

**Comment by bmarty** [comment] 2023-10-04 14:40
Thanks @sandhose .

According to [the doc](https://developer.android.com/training/app-links/index.html#android-app-links) you are linking: `So when the user clicks on an Android App Link`. Here the user does not click anything, so it's maybe the source of the issue? How is invoked the redirectUri with the param by the MAS page?

**Comment by sandhose** [comment] 2023-10-04 14:49
@bmarty I'm doing a HTTP redirect using the status code `303 See Other`.

Looks like in the AppAuth-Android library, they have a [separate activity](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/RedirectUriReceiverActivity.java) declared in the manifest, instead of launching the main activity. Could you try something similar?
https://github.com/openid/AppAuth-Android/blob/master/app/AndroidManifest.xml#L59-L70

**Comment by bmarty** [comment] 2023-10-04 19:59
Thanks. The [doc](https://github.com/openid/AppAuth-Android#capturing-the-authorization-redirect) recommend to use custom scheme and I tend to agree with this:

> We recommend using a custom scheme based redirect URI (i.e. those of form my.scheme:/path), as this is the most widely supported across all versions of Android.

Also, a bit later in the same README

> We recommend that a fallback page be configured at the same address to forward authorization responses to your app via a custom scheme, for older Android devices.

Do we have this? I also understand that if we support `https` redirection, the Android app should support the custom scheme.

**Comment by pixlwave** [comment] 2023-10-09 10:38
> @pixlwave did you have the same issue on iOS?

Sorry late to the party here, yes we essentially had the same on iOS. We already had the associations on mobile.element.io (although they needed some fine tuning to work with app normal/nightly/pr builds) so it just needed some extra code to complete the auth request when the callback comes in to the app as universal link instead of being caught within the web auth session view.

**Closed as completed** 2023-12-05 15:16 UTC
Labels: S-Tolerable, O-Occasional, A-OIDC
