### ISSUE TITLE
FOSS Version

### ISSUE THREAD

**Issue by Sir-Photch** [element-hq/element-x-android#1418] opened 2023-09-24 15:21 UTC
Hi, I wanted to raise some awareness for some objectives that the Android-FOSS community would enjoy seeing. Those are:

1. Support for ntfy-push. This should count as the greatest FOSS-priority.
2. Non-Fdroid FOSS releases, preferrably on GitHub
3. Split APKs

About Nr. 2: While Element-Android has github releases that one can use, they only provide the playstore version of the app. Furthermore, the version available on fdroid often lags behind playstore by a significant timespan. You might make the argument that fdroid only receives stable versions of the app after being tested by playstore users; However for pre-releases, github already provides the necessary facilities. 

I hope this could gain some traction in the early development of Element-X.

**Comment by bmarty** [comment] 2023-10-09 07:21
Hello,

This is the tasks to achieve to be able to publish on F-Droid:
- [ ] Add gradle`flavorDimensions` store with two values `gplay` and `fdroid`
- [ ] Update all the CI script so that it understand this new `flavorDimensions` and build both variant
- [ ] Assign value to `BuildMeta.flavorDescription` and `BuildMeta.flavorShortDescription` ([here](https://github.com/vector-im/element-x-android/blob/develop/app/src/main/kotlin/io/element/android/x/di/AppModule.kt#L84))
- [ ] Bug report: uncomment `builder.addFormDataPart("label", buildMeta.flavorDescription)` ([here](https://github.com/vector-im/element-x-android/blob/develop/features/rageshake/impl/src/main/kotlin/io/element/android/features/rageshake/impl/reporter/DefaultBugReporter.kt#L296))
- [ ] Make sure the `fdroid` variant does not include the module `pushproviders.firebase`
- [ ] Make sure the `fdroid` variant configure properly the unified push provider. UnifiedPush support has been implemented and has to be used at [this point](https://github.com/vector-im/element-x-android/blob/develop/appnav/src/main/kotlin/io/element/android/appnav/loggedin/LoggedInPresenter.kt#L44). Note: if there is no installed distributors, no pusher will be registered. There is no UI to select a push provider and a distributor for now, this is out of scope of this issue.
- [ ] When it's ready, ping the F-Droid team to make them build the app and publish it.

Already done:
- [ ] The store assets are already [committed in the project](https://github.com/vector-im/element-x-android/tree/develop/fastlane/metadata/android/en-US), this must be used to publish to the F-Droid store. (English only for now)

In the long term: Element X Android codebase will be used to upgrade Element Android (the existing app). So at some point this work has to be done, to be able to release the new Element Android to F-Droid

**Comment by licaon-kter** [comment] 2023-10-09 12:07
Current status is rather clean ( ahem https://gitlab.com/fdroid/rfp/-/issues/2556#note_1593343486 ), I mean one `rm` and 3 `sed`s, but yeah, a flavor would be nicer so we don't need to hunt down future changes :wink:

**Comment by licaon-kter** [comment] 2024-01-20 13:23
@Mynacol think you are missing same context.

If this app is repro, great.

But this app will die after a while and current app (non X) will be replaced with this one.

Yet, to have that reproducible then, all the current users will need to uninstall & reinstall.

There's no UI that informs as such and guide the users, at least not yet.

The TWIF (this week in fdroid) blog posts are used to inform about such changes but not sure everybody is RSS subscribed to that :)

**Comment by K4LCIFER** [comment] 2024-02-01 06:58
[It looks like](https://matrix.org/blog/2024/01/26/this-week-in-matrix-2024-01-26/) Element X is to be published to F-Droid, with support for UnifiedPush, for the release of v0.4.2.

**Comment by licaon-kter** [comment] 2024-02-01 08:35
@K4LCIFER read this thread at least https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13829#note_1595843143 maybe https://gitlab.com/fdroid/rfp/-/issues/2556 too

**Comment by Mek101** [comment] 2024-03-16 11:42
Only another 20 thousand years...

**Comment by SamyDjemai** [comment] 2024-03-22 10:13
Hi @bmarty, from what I see in [LoggedInPresenter.kt](https://github.com/vector-im/element-x-android/blob/develop/appnav/src/main/kotlin/io/element/android/appnav/loggedin/LoggedInPresenter.kt#L44) and in my tests, the UnifiedPush provider seems to be properly working now. Is there any other steps we can help you with before pinging the F-Droid team? :)

**Comment by licaon-kter** [comment] 2024-03-22 10:16
@SamyDjemai ping who about what? https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13829

**Comment by licaon-kter** [comment] 2024-03-22 10:26
Expand the threads and read F-Droid feedback and ara4n's answers, that's the status I guess...

> would we need to change something in this repo to comply?

yes, a place for F-Droid to grep the versionName and versionCode

**Comment by SamyDjemai** [comment] 2024-03-22 11:25
I think that instead of hardcoding the versionName and versionCode in this repo, we could use [UpdateCheckData in HTTP mode](https://f-droid.org/en/docs/Build_Metadata_Reference/#UpdateCheckData) and scrape the GitHub API for latest releases.
As an example, we could have:
```yaml
UpdateCheckMode: HTTP
UpdateCheckData: https://api.github.com/repos/element-hq/element-x-android/releases?per_page=1|"tag_name": "v((?:[0-9]\d*)\.(?:[0-9]\d*)\.(?:[0-9]\d*))"|.|"name": "(\d+)
```
This way, the release process stays unchanged, and we can dynamically fetch versionName and versionCode

**Comment by licaon-kter** [comment] 2024-03-22 11:50
@SamyDjemai that line yields `ruamel.yaml.scanner.ScannerError: mapping values are not allowed in this context` so it might need some tweaking :)

**Comment by jspricke** [comment] 2024-03-22 12:20
This works for me:
```
UpdateCheckData: 'https://api.github.com/repos/element-hq/element-x-android/releases?per_page=1|"name":"(\d+)|.|"tag_name":"v((?:[0-9]\d*)\.(?:[0-9]\d*)\.(?:[0-9]\d*))"'
```

**Comment by SamyDjemai** [comment] 2024-03-22 12:33
I've also reworked mine with simpler matching :)
```yaml
UpdateCheckMode: HTTP
UpdateCheckData: https://api.github.com/repos/element-hq/element-x-android/releases/latest|"name":"(\d+)-|.|"tag_name":"v(\d+\.\d+\.\d+)"
```

I'd suggest using `https://api.github.com/repos/element-hq/element-x-android/releases/latest` instead of using the `?per_page=1`.

I'm getting this error:
```
2024-03-22 12:32:41,036 ERROR: ...checkupdate failed for io.element.android.x : current version is newer: old vercode=40004064, new vercode=40004060
```
@licaon-kter would we track specific commits of the repo, or only releases? If we do the latter, we should clean up the `Builds` section of the manifest file

**Comment by licaon-kter** [comment] 2024-03-22 12:38
> I'm getting this error:

I've fixed that, let me test the rest

**Comment by SamyDjemai** [comment] 2024-03-22 12:45
What if we use `AutoUpdateMode: Version v%v`? According to [this documentation](https://f-droid.org/en/docs/Build_Metadata_Reference/#AutoUpdateMode), we can directly use the version tag, and we don't need the commit hash

**Comment by SamyDjemai** [comment] 2024-03-22 12:47
But the Git tags are in the `vX.X.X` format, hence the need for `v%v` if I'm not mistaken, since according to the doc:
> The pattern is used to generate a value (tag name) used for the commit: property of new build blocks. It is simply text in which %v and %c are replaced with the required version name and version code respectively. The resulting string must match an existing tag in the app’s repo, which then will be used by F-Droid to build the corresponding version.

**Comment by licaon-kter** [comment] 2024-03-22 12:51
yup that does it

```
...
AutoUpdateMode: Version v%v
UpdateCheckMode: HTTP
VercodeOperation:
  - 1 + %c
  - 2 + %c
  - 3 + %c
  - 4 + %c
UpdateCheckData: https://api.github.com/repos/element-hq/element-x-android/releases/latest|"name":"(\d+)-|.|"tag_name":"v(\d+\.\d+\.\d+)"
CurrentVersion: 0.4.6
CurrentVersionCode: 40004064
```

**Comment by SamyDjemai** [comment] 2024-03-22 13:54
Great, thanks! From what I've assessed, in order to be compliant with F-Droid's inclusion policy, we still need to do the following:

- [ ] build F-Droid version without proprietary components
  - [ ] Sentry: remove `services/analyticsproviders/sentry` in the F-Droid manifest
  - [x] Mapbox: Maplibre is used
- [ ] get approval from the upstream team for F-Droid release (clear up the existing confusion regarding release)

@licaon-kter do you see any other blockers?
@bmarty is the Element X team OK for F-Droid release?

**Comment by licaon-kter** [comment] 2024-03-22 15:07
> build F-Droid version without proprietary components 

current recipe does that

> Sentry: remove services/analyticsproviders/sentry in the F-Droid manifestJ

not a NEED, if it's on by default or opt-out, it will get a Tracking anti-feature, if it's off by default and opt-in, it will get nothing

>  get approval from the upstream team for F-Droid release (clear up the existing confusion regarding release)

mostly this yes

> reproducible builds

the big IF

**Comment by SamyDjemai** [comment] 2024-03-22 16:43
Nice catch, forgot that the Sentry SDK is open source :facepalm: 
There is an opt-in screen for tracking when first logging into the app, so there won't be a Tracking anti-feature.

> reproducible builds

The "current" Element app currently doesn't have reproducible builds, but there will be no need to uninstall and reinstall for users [as you mentioned here](https://github.com/element-hq/element-x-android/issues/1418#issuecomment-1902093329) if we implement them later and publish both developer-signed and F-Droid-signed APKs, right?

In my opinion, reproducible builds are a nice-to-have feature regarding the "temporary" nature of this app, but they aren't a priority. The 52 people that liked the issue's first message probably just want to try out Element X, no matter if it has reproducible builds or not.

**Comment by Mek101** [comment] 2024-03-22 17:25
> The 52 people that liked the issue's first message probably just want to try out Element X, no matter if it has reproducible builds or not.

I just want to try Element X without having the burden of keeping track of each release

**Comment by SamyDjemai** [comment] 2024-03-25 10:00
> However, there is exactly one time slot to determine which type of reproducible builds we choose for this app: before the first release in F-Droid.

While I agree with that, the plan for this app is for it to replace the existing Element app in app stores and in F-Droid, so even if we set up reproducible builds *here* before first release, we're still going to have to deal with an existing app that was already built and deployed before reproducible builds were set up.

That's why, in my opinion, they are nice-to-have, especially in this repo which is meant to be temporary.

> adding reproducible builds later requires to manually add signature information for each new release

That's problematic, but from what I understand based on [the GitLab pull request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13829/diffs#fe0a264638334c40c063bbcf8dbdfaa18144e3c7_0_76), updates won't be automated anyways

**Comment by linsui** [comment] 2024-03-25 13:28
Reproducible Build doesn't only allow the user to install the apk from different channels, but also make sure that the apk built by F-Droid has no bug introduced by F-Droid. So F-Droid doesn't need to set a user agent for bug reports.

> Please can you ensure that you set a user agent which clearly identifies the app as being the Fdroid build (so we can differentiate bug reports & debug appropriately)

**Comment by licaon-kter** [comment] 2024-05-23 15:46
well well well... I might even check that reproducibility then, brb

**Comment by licaon-kter** [comment] 2024-05-23 17:39
First result
```
Unexpected diff output:                                    Binary files /tmp/tmpx353fgjh/unsigned_binaries_io.element.android.x_40004132.binary/content/AndroidManifest.xml and /tmp/tmpx353fgjh/_tmp_tmpx353fgjh_sigcp_io.element.android.x_40004132/content/AndroidManifest.xml differ               Binary files /tmp/tmpx353fgjh/unsigned_binaries_io.element.android.x_40004132.binary/content/assets/dexopt/baseline.prof and /tmp/tmpx353fgjh/_tmp_tmpx353fgjh_sigcp_io.element.android.x_40004132/content/assets/dexopt/baseline.prof differ                                                          Binary files /tmp/tmpx353fgjh/unsigned_binaries_io.element.android.x_40004132.binary/content/classes.dex and /tmp/tmpx353fgjh/_tmp_tmpx353fgjh_sigcp_io.element.android.x_40004132/content/classes.dex differ                               Binary files /tmp/tmpx353fgjh/unsigned_binaries_io.element.android.x_40004132.binary/content/classes3.dex and /tmp/tmpx353fgjh/_tmp_tmpx353fgjh_sigcp_io.element.android.x_40004132/content/classes3.dex differ                             Binary files /tmp/tmpx353fgjh/unsigned_binaries_io.element.android.x_40004132.binary/content/resources.arsc and /tmp/tmpx353fgjh/_tmp_tmpx353fgjh_sigcp_io.element.android.x_40004132/content/resources.arsc differ
```
...will diff the APKs later

**Comment by licaon-kter** [comment] 2024-05-23 18:42
In the meantime, the starting flow is funny/sad, always pushing the central server:
* welcome
* want matrix.org?
* no, change host
* choose matrix.org?
* no, please other
* enter host...
* aaa
* trying to connect to `aaa.com` in background
...

**Comment by licaon-kter** [comment] 2024-05-23 19:26
Love you too thumbdowners :smile:

Anyway, @bmarty, the diff log for arm64 is small so we are close to being repro, all seem easily fixed: [-uyVTbKjT3qFQHpitMUYEg.log](https://github.com/element-hq/element-x-android/files/15421664/-uyVTbKjT3qFQHpitMUYEg.log)

**Comment by licaon-kter** [comment] 2024-05-24 08:35
Maybe reopen until those 2-3 repro issues get fixed?

**Comment by licaon-kter** [comment] 2024-05-24 09:35
> The values are store as GitHub secret so you do not have it when you build yourself.

https://f-droid.org/docs/Inclusion_Policy/
> F-Droid does not sign up for any API keys. Even if provided by a third party, we include them in both, binary and sourcecode releases.

they need to be here in your code or in the F-Droid recipe, no secrets allowed

> Is it possible that your build chain patch the code [here](https://github.com/element-hq/element-x-android/blob/develop/plugins/src/main/kotlin/extension/Utils.kt#L40)?
> So in your case the line will change from

we can do, yes

> I am still investigating this.

great

**Comment by bmarty** [comment] 2024-05-24 10:02
> they need to be here in your code or in the F-Droid recipe, no secrets allowed

Yes, you can put the values in the F-Droid recipe, and set environment variables as described, this is fine (sorry if it was not clear). The 3 values are in the diff you provided.

Alternatively, you can put the values in the `local.properties` file. The values are read [here](https://github.com/element-hq/element-x-android/blob/develop/features/location/api/build.gradle.kts#L35) and it's documented [here](https://github.com/element-hq/element-x-android/blob/develop/docs/maps.md).

**Comment by bmarty** [comment] 2024-05-24 13:25
https://github.com/element-hq/element-x-android/pull/2911 should help on the `versionCode` diff.

**Comment by bmarty** [comment] 2024-05-27 12:34
@licaon-kter #2911 has been merged, so I think the plan for us is to publish F-Droid APKs for the next release on Github v0.4.14. This should occur on June 4th.

On your side: change the recipe about the 2 points mentioned above: the map keys and the git branch name.

Hopefully the APKs will have the reproducible validation green flag.

**Comment by licaon-kter** [comment] 2024-05-27 13:12
I've already tested the map injection fix, will test the test when the Tag drops. Feel free to ping me.

**Comment by licaon-kter** [comment] 2024-06-06 08:27
@bmarty tick-tock, 4-th was gone

**Comment by bblacher** [comment] 2024-06-07 10:49
@licaon-kter They just bumped the version, in a few minutes the release will be out. https://github.com/element-hq/element-x-android/commit/4b27cda15c478049b7f6c2f2ab3b3a657a270af2

**Comment by licaon-kter** [comment] 2024-06-07 13:26
Started a build

First issue though, I can't know the versionCode for autoupdates, we used to pick it up from the APK name in past releases, eg. https://github.com/element-hq/element-x-android/releases/tag/v0.4.13 ->  40004130.apk  -> `40004130`

but that's not a thing in latest https://github.com/element-hq/element-x-android/releases/tag/v0.4.14

**Comment by ganfra** [comment] 2024-06-07 14:09
Ok, can rename the file.

**Comment by licaon-kter** [comment] 2024-06-07 14:12
Ok, thanks, the question is, do you need that file or? maybe there's a way to name it so it usable both by F-Droid and users that drop by (eg. Obtainium etc)

**Comment by ganfra** [comment] 2024-06-07 14:34
This is the universal apk for gplay variant. I just renamed it manually so it was clear. The original name is the one provided by the playstore.

**Comment by licaon-kter** [comment] 2024-06-07 15:14
Here's the first diff log: [elem0414_2.log](https://github.com/user-attachments/files/15741589/elem0414_2.log)

this looks like https://f-droid.org/docs/Reproducible_Builds/#embedded-build-paths with some ways to fix it here: https://gist.github.com/obfusk/61046e09cee352ae6dd109911534b12e

not sure if the AndroidManifest.xml will be fixed too once baseline is

**Comment by linsui** [comment] 2024-06-07 15:28
Given that we can't get the release files without using the api which is rate limited, can you add a version.txt with version code in it?

**Comment by licaon-kter** [comment] 2024-06-08 10:21
This has been merge in F-Droid metadata :fireworks:

FYI https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client


/close this

**Comment by bmarty** [comment] 2024-06-13 12:57
Thanks! I was actively waiting for https://f-droid.org/packages/io.element.android.x/ to return something.
Let's close the issue, please open new issues in case of trouble.

**Closed by bmarty** 2024-06-13 12:57 UTC
Labels: T-Enhancement, A-Push, A-Store-F-Droid

**Comment by licaon-kter** [comment] 2024-06-13 13:01
@networkException if you installed in the past from my builds then that's expected

F-Droid hosts the verified reproducible builds from upstream now.

**Comment by licaon-kter** [comment] 2024-06-13 13:02
@bmarty it does now, it takes a bit more after the index is published for the website to be generated

**Comment by networkException** [comment] 2024-06-13 13:03
@licaon-kter Should've been from the Google Play previously. Is upstream signing these differently?
