### ISSUE TITLE
Verification fails with endless spinner

### ISSUE THREAD

**Issue by axelsimon** [element-hq/element-x-android#1189] opened 2023-08-30 12:10 UTC
### Steps to reproduce

Tried to follow the verification steps, as prompted.

Other devices tried are Element Desktop (flatpak, Element version: 1.11.39 on Fedora 38) and Element web (develop.element.io, Element version: 19b2eded16db-react-6cc42b7e2e03-js-f406ffd3dd14).

I get prompted to verify session on Desktop, am offered emoji verification (and only emoji verification, even though my phone has a camera).

After clicking start, i just get endless spinners on both sides:
"Waiting to accept request" on the Android side.
"Verify other device" on the Desktop side.

Happy to try and provide logs, but currently rageshaking in Element X Android does nothing. I can `adb logcat` if given a good set of filters.

#### What did you expect?
QR code verification.
If emoji verification, working verification flow.

#### What happened instead?
Got stuck trying to verify the device.

### Your phone model

Pixel 2

### Operating system version

GrapheneOS (Android 11)

### Application version and app store

0.1.5 (40001050) from Play Store (via Aurora Store)

### Homeserver

element.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment] 2023-08-30 14:08
For reporting a bug without rageshaking, you can go to `Settings` by tapping on your avatar in the home screen and then 'report bug'.

Would you be able to reproduce this bug again?

**Comment by kittykat** [comment] 2023-10-06 08:49
@axelsimon Hi, just wanted to check if you would be able to follow up on this issue? Unfortunately we cannot investigate it any further without the logs.

**Comment by blegat** [comment] 2023-10-20 08:11
I have the same issue, I reported the bug with the "Report bug" button and described it as "Same as issue #1189". Let me know if I can do anything to help.

**Comment by manuroe** [comment] 2024-03-26 16:54
@axelsimon , @blegat do you still see this problem?

**Comment by blegat** [comment] 2024-03-27 06:54
Just tried now with Element X v0.4.6 on Android 13 (Fairphone 4 with version FP4.TP29.C.0101) with element-desktop v1.11.58-1 on ArchLinux and it worked, it continued to the verification with 5 emojis (it didn't go through that step before) and now it's verified :)

**Comment by manuroe** [comment] 2024-03-27 13:48
Thanks @blegat . We made several changes in this area since the original report. Let's close this bug.

**Closed by manuroe** 2024-03-27 13:48 UTC
Labels: S-Critical, T-Defect, O-Occasional, A-E2EE-Cross-Signing, A-E2EE, X-Needs-Info
