### ISSUE TITLE
Line breaks are ignored in timeline

### ISSUE THREAD

**Issue by VolkerJunginger** [element-hq/element-x-android#1882] opened 2023-11-24 12:01 UTC
### Steps to reproduce

Create a message with line breaks.
Send the message.
The line breaks are not considered when displaying the message in the timeline.

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by manuroe** [comment] 2023-12-01 10:27
@jmartinesp will check on the Android side.

**Comment by Velin92** [comment] 2023-12-01 18:47
Okay so the issue seems to only happen when the RTE is off, and only **for the first line**.
This is caused because because the SDK converts the markdown for text that looks like this:
```
line1

line2

line3
```
as: `<p>line1</p>\n<p>line2<\p>\n<p>line3<\p>`

Which should be fine in theory, but since to render bidirectional text properly with the timestamp, we actually always prefix with a unicode character that represents the current layout direction, this breaks only the first line.

If we remove this character we can fix the issue, but we will revert bidi text to look like this (when both RTL and LTR are mixed):
![Image](https://github.com/vector-im/element-x-android/assets/34335419/a2e6c6cb-3005-4390-923a-d6520bf1c5ca)

Which clashes with the timestamp.

This is a niche use case so maybe we can remove the prefix for now, while we work on a better way to handle the timestamp (since it is kinda appended at the bottom with a trick but maybe we should use something smarter like an attributed string, or smart layout?)


Another solution is to change how the rust side interprets the markdown content to change:
 `<p>line1</p>\n<p>line2<\p>\n<p>line3<\p>` into
`<p>line1</p><br><p>line2<\p><br><p>line3<\p>`
Which is probably also not too hard to do

Also there is the possibility (but would fix the issue only between El-X client) to always send formatted content when in markdown mode but RTE has some issues when is se to work in markdown mode on its own instead of using the rust sdk markdown converter.

@pixlwave @stefanceriu @manuroe 
Let me know what you guys think.

**Comment by Velin92** [comment] 2023-12-11 15:19
Fixed by also keeping RTL working properly by just replacing </p>\n<p> with two <br> 
https://github.com/vector-im/element-x-ios/pull/2224

**Comment by VolkerJunginger** [comment] 2023-12-13 08:48
not working ion my Android

**Comment by jmartinesp** [comment] 2023-12-14 07:51
@VolkerJunginger could you try again with today's nightly? We completely replaced the rendering for text messages, and I can't reproduce this myself anymore.

**Closed** 2023-12-15 10:39 UTC
Labels: S-Major, T-Defect, O-Frequent, A-Rich-Text-Editor, X-Needs-Signoff
