### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by amosstevens** [element-hq/element-x-android#2346] opened 2024-02-05 07:46 UTC
Android 13 
(GrapheneOS, TP1A.221005.002.B2.2024010700)
Google Pixel 4
Element X 0.4.2 (Github APK)

The application crashes on start

that's the log

https://privatebin.io/?01d88089a93ef677#9Eco1kUYEGHBChVMzKYN3D1PXEQV3KS2GJcgPQJfBZ6r

**Comment by jmartinesp** [comment] 2024-02-07 09:37
This seems related to the `Cleaner` API changes in the latest uniffi version, but I don't see why creating a `Cleaner` instance would fail, to be honest. It'll need more investigation...

**Comment by jmartinesp** [comment] 2024-02-07 09:48
It seems like this is caused by some code that was later removed in AOSP: https://android.googlesource.com/platform/libcore/+/cb89eca6d568e8c330f9e3c61b714fbfd0a304a5%5E%21/#F2

I can't reproduce it in an Android 13 emulator: are you using a custom ROM or have a rooted phone with some Magisk modules or something that attaches itself to the Zygote process? (if you don't know what any of those are, then you probably don't).

**Comment by amosstevens** [comment] 2024-02-07 10:10
I'm using the latest GrapheneOS for Pixel 4

**Comment by amosstevens** [comment] 2024-02-08 11:07
ElementX 0.4.1 was working well, the crash happened when i updated it to the 0.4.2 version

**Comment by jmartinesp** [comment] 2024-02-08 11:22
> ElementX 0.4.1 was working well, the crash happened when i updated it to the 0.4.2 version

I believe that's because that the version is the first one using a Rust SDK back by UniFFi 0.26.0, which added this new API.

I took a look at the GrapheneOS sources and it seems like the code that should fix this was added a year ago: https://github.com/GrapheneOS/platform_libcore/commit/cb89eca6d568e8c330f9e3c61b714fbfd0a304a5

It seems like it's not part of GrapheneOS 13. I'm not sure if that's expected, I'd have to double check with the AOSP code. If it is, the UniFFi code would have to be changed so that API is only used on Android 14+. However, as stated above I can't reproduce it in an Android 13 emulator, which is super weird, and I don't have a device with that version to check if the problem exists in an actual Android 13 ROM other than GrapheneOS.

**Comment by SamyDjemai** [comment] 2024-03-17 12:57
Looking at [this commit](https://android.googlesource.com/platform/libcore/+/e456f07cf53abb767ee81908301c4327e716cbd2%5E2..e456f07cf53abb767ee81908301c4327e716cbd2/), it looks like that AssertionError was removed in Android 14+ and not 13, judging by the commit date and comparing to the release branches' latest commits.
As for UniFFi, I suspect [this commit](https://github.com/mozilla/uniffi-rs/commit/f5fc9d7e9aa08889aedc45dd81ae9b4d3ec4cbe8) to be the source of this issue. I'll open an issue referencing this one on the repo.

**Comment by SamyDjemai** [comment] 2024-03-19 14:02
https://github.com/matrix-org/matrix-rust-sdk/pull/3235 was merged, and after building and running a debug version of the app on my phone, it launches and works properly :tada: 

As a result, the next release that uses the updated version of `matrix-rust-sdk` should work on GrapheneOS 13.

**Comment by jmartinesp** [comment] 2024-03-20 11:57
A new SDK version was merged into `develop`, so the tomorrow's nightly should have the fix.

**Comment by manuroe** [comment] 2024-03-27 13:49
thanks @SamyDjemai for testing the change.

**Closed by manuroe** 2024-03-27 13:49 UTC
Labels: S-Critical, T-Defect, O-Uncommon, z-Crash
