### ISSUE TITLE
Element call: give audio feedback while waiting

### ISSUE THREAD

**Issue by frandavid100** [element-hq/element-x-android#3849] opened 2024-11-09 22:35 UTC
#### What would you like to do?

When I call someone through Element Call, I want to be able to tell when the other person has picked up without having to stare at the screen.

#### Why would you like to do it?

Because I want to be able to look elsewhere while I wait.

#### How would you like to achieve it?

I'd like Element X to behave like other apps: ring while you're waiting for someone to pick up, stop ringing (and maybe give some additional audio feedback) when someone picks up.

### Are you willing to provide a PR?

Yes

**Comment by rajil** [comment] 2024-11-11 03:31
This is a duplicate of [this](https://github.com/element-hq/element-call/issues/926).

**Comment by frandavid100** [comment] 2024-11-11 03:36
> This is a duplicate of [this](https://github.com/element-hq/element-call/issues/926).

They look like completely different issues to me.

**Comment by rajil** [comment] 2024-11-11 03:58
[This](https://github.com/element-hq/element-call/issues/2720)?

**Comment by frandavid100** [comment] 2024-11-11 04:13
> [This](https://github.com/element-hq/element-call/issues/2720)?

OK, now this is the same issue. Thanks!

**Comment by toger5** [comment] 2024-11-18 09:51
Close as duplicate (see prev messages).

**Closed by toger5** 2024-11-18 09:51 UTC
Labels: T-Enhancement
