### ISSUE TITLE
History missing in EXA public room

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-android#1076] opened 2023-08-17 21:14 UTC
### Steps to reproduce

the history was there, but when I left and came back to the app I watched it vanish

https://matrix.to/#/!aCvOWKNDeXXpPgquKq:matrix.org/$m-bhJJ48WIdjFMnEdDB50_hP5hpsqf5T3uTv3V-wP58?via=matrix.org&via=envs.net&via=element.io

#### What did you expect?

History should never spuriously vanish

### Application version and app store

playstore 0.1.2 (40001020)

### Homeserver

pintobyte.com

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jonnyandrew** [comment] 2023-08-25 09:59
Removing the _needs rust_ label until we know enough to create an upstream issue.

**Comment by manuroe** [comment] 2023-09-13 08:55
Assigned to me to check rageshakes

**Comment by manuroe** [comment] 2023-09-15 15:50
I checked rageshakes we received. We have 2 persons experiencing problems on their own homeserver & SS proxy. No-one is complaining on matrix.org since we fixed problems initially reported on iOS in https://github.com/vector-im/element-x-ios/issues/1197. 
This issue might be a server version problem.

We are aware that the [workaround](https://github.com/matrix-org/matrix-rust-sdk/issues/2261) we made in SDK can generate false negative `limited` but we have not seen problem yet. The true now fix is to implement `limited` on the [proxy](https://github.com/matrix-org/sliding-sync/issues/197). 

I am deprioritising the issue. We can really work on such issue by checking both backend and client logs.

**Comment by 0ranki** [comment] 2023-09-19 19:34
Ran into the issue on 0.2.0, custom homeserver too. I sent a bug report from EXA, hopefully you can connect it here. Faced the same on the version in Play Store at the time of writing (0.1.6, I think)

I opened the app right around 18:55 in the timezone on the log file:
[ss-proxy.log](https://github.com/vector-im/element-x-android/files/12665755/ss-proxy.log)

Unfortunately it's only INFO level, I'll raise the verbosity and see if I get the issue again and would be able to get the SS proxy logs.

The last time I faced the issue on the older version, I think I also had posted something and someone replied, but didn't react to it at that time.

I had notifications turned off for the room at this time, if that makes a difference.

**Comment by timokoesters** [comment] 2023-09-22 11:06
I've seen multiple versions of this bug when I was testing on Conduit.
1. Some messages of the history are missing, probably a single batch, but it continues normally after that
2. I can only see a few most recent events and the history before that doesn't load at all, it's just white.

I can reproduce number 2 on both conduit and matrix.org by
- fully closing the app 
- send two messages to my element x account in a DM
- clicking on the notification to start the app again

**Comment by manuroe** [comment] 2023-09-22 11:58
An idea raised when discussing this problem on matrix with @bnjbvr :

Can it be a late keys decryption issue? Like in this flow:
- on app resume, `/sync` returns some messages but not the corresponding new keys
- EAX decides to not display them as UTDs for an unknown reason
- keys arrive
- Messages are decrypted in the SDK
- BUT EAX does not update the timeline with decrypted content. Maybe it updates the timeline items but they stay hidden

We start thinking this is an application problem because iOS do not have this issue.

**Comment by bnjbvr** [comment] 2023-09-22 12:00
Not a late decryption, I think: there were messages that I had seen in the room before. I background the app. I receive a notification from the app for new messages in this room. I click the notification, thus enter the room. After entering the room, some messages I had seen before backgrounding are now missing.

If I get back to the room list, then into the room again, I can see those messages perfectly fine.

**Comment by timokoesters** [comment] 2023-09-22 12:25
Here's how I can reproduce the bug number 2 I mentioned. It does not work every time:
https://github.com/vector-im/element-x-android/assets/25297359/4df0cc1e-49bb-4c73-9ce9-0fe8ec58a3de

**Comment by bnjbvr** [comment] 2023-09-22 13:50
@timokoesters Thanks for the repro. Is that with a Synapse + sliding sync proxy server?

**Comment by timokoesters** [comment] 2023-09-22 13:52
@bnjbvr Yes, the recording is from a matrix.org account

**Comment by bnjbvr** [comment] 2023-09-22 13:52
Cool, thanks for confirming. Also concurrently I did reproduce the issue with my Synapse + sliding sync proxy instances, using your STRs. Thanks a bunch :pray:

**Comment by bnjbvr** [comment] 2023-09-22 16:19
From watching lots of logs, I suspect the following happens:

- a back-pagination may start in the room we're looking at
- sliding sync starts, or was running in the background
- server returns 1 event aka the latest message) that the SDK wasn't aware of; the sliding sync proxy is right, here, since we knew about all the previous messages
- client-side `limited` computation concludes it may be a `limited` timeline: there's only one event in the response that it doesn't know about
- that in turn clears all the timeline items _while_ the timline is being back-paginated :boom: 

With respect to the progression of the back pagination, the clearing of the timeline may happen before/after/in the middle of pagination, likely resulting in missing messages.

cc @jplatte

**Comment by jplatte** [comment] 2023-09-22 16:58
That sounds realistic. So I think we have to cancel the ongoing back-pagination, if any, when the timeline is reset, right?

**Comment by timokoesters** [comment] 2023-09-22 21:03
If you click on a notification, you probably want to see the message context and not cancel backpropagation @jplatte

Would it be possible to recover from the limited timeline instead of reconstructing it? Or alternatively to reconstruct it in the background so the user doesn't notice.

**Comment by jplatte** [comment] 2023-09-23 06:42
@timokoesters eventually, we will be able to handle limited server responses more gracefully than resetting the timeline. There are plans, but they're not simple because we're dedicated to doing things right.

**Comment by jmartinesp** [comment] 2023-10-06 10:04
This was supposed to be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2638, but apparently the issue still exists. Do we still think this is a Rust only issue? Is there anything we can do to help investigating this issue?

**Comment by jplatte** [comment] 2023-10-06 10:08
A new rageshake from a room where the problem happened, one that I'm in or that is public, might be helpful. Also wouldn't hurt to add `matrix_sdk_ui::timeline=trace` to the tracing filter.

**Comment by anoadragon453** [comment] 2023-10-06 10:34
Is this related to https://github.com/vector-im/element-x-android/issues/1281? I posted a sliding sync server log in there if helpful.

**Comment by jplatte** [comment] 2023-10-06 10:39
I initially thought so, but https://github.com/matrix-org/matrix-rust-sdk/pull/2638 should have fixed this if that was the case.

**Comment by bmarty** [comment] 2023-10-12 12:31
Fixed in EXA 0.2.4

**Comment by kittykat** [comment] 2023-10-26 12:48
If anyone is seeing this issue with the latest nightly, please rageshake as we need new logs to investigate further

**Comment by jplatte** [comment] 2023-10-26 16:10
Additionally, it would be helpful if bug reports included the event IDs of the last event before the gap + first event after the gap. (for public rooms, a screenshot also works)

**Comment by davidmehren** [comment] 2023-10-30 12:49
I just experienced this issue again and submitted a rageshake with event IDs

**Comment by manuroe** [comment] 2024-03-27 15:30
This should not happen anymore. Reopen if it is not the case.

**Comment by Xiretza** [comment] 2024-03-28 19:11
Unless this was supposedly fixed between 0.4.7 and latest develop, can somebody reopen?

**Comment by Xiretza** [comment] 2024-03-29 10:59
Not really, unfortunately, it just happens seemingly randomly every once in a while. Might have something to do with my slow-as-molasses sliding sync proxy.

**Comment by manuroe** [comment] 2024-03-29 13:32
@Xiretza: Can you please a bug report when it happens? It would be useful to provide the room id and an id of the event that is missing.

Can you also check that the missing messages do not appear in the wrong position in the timeline like in https://github.com/element-hq/element-x-android/issues/1881?

**Comment by manuroe** [comment] 2024-06-26 15:07
No new feedback. Closing.

**Closed by manuroe** 2024-06-26 15:07 UTC
Labels: S-Critical, T-Defect, O-Uncommon, A-Timeline, X-Needs-Rust, X-Needs-Info
