### ISSUE TITLE
In certain cases, the timeline position cannot be remembered.

### ISSUE THREAD

**Issue by YamatoRyou** [element-hq/element-x-android#3454] opened 2024-09-12 13:20 UTC
### Steps to reproduce

1. Go to the timeline of any room;
2. Scroll up a certain distance, the longer the better;
3. Click the room title;
4. Go back and return to the timeline.

#### What did you expect?
Stay at the current position;

#### What happened instead?
Go back to the timeline, always automatically jump to the end of the timeline.

### Your phone model

OnePlus 9RT (MT2110)

### Operating system version

Pixel OS (Android 14)

### Application version and app store

Element X for Android 0.6.0

### Homeserver

Synapse 1.114.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by claell** [comment] 2024-09-13 07:41
Sounds like a duplicate of #2268.

**Closed** 2024-09-18 18:50 UTC
Labels: T-Defect
