### ISSUE TITLE
Message bubbles render trailing newlines from formatted HTML body

### ISSUE THREAD

**Issue by frebib** [element-hq/element-x-android#2099] opened 2023-12-23 11:51 UTC
I wouldn't expect such a tall bubble here. The timestamp also looks too far left which is maybe causing this?
![Screenshot_20231223-114648.png](https://github.com/element-hq/element-x-android/assets/775104/cff5136f-9592-4233-a53b-f6f10a7a0490)

```
{"type":"m.room.message","sender":"@echo:nerdhouse.io","content":{"msgtype":"m.notice","body":"a","format":"org.matrix.custom.html","formatted_body":"\u003cp\u003ea\u003c/p\u003e\n"},"origin_server_ts":1703325271499,"unsigned":{"age":93},"event_id":"$Tkq2w8nsVlVnOMcWM9bDX5c_unMN-he2qi6CDg8QP90"}
```

This is the first nightly after 0.4.0

**Comment by frebib** [comment] 2023-12-23 21:22
I've seen this happen with single emojis and even rich-formatted messages that are short too

**Comment by bmarty** [comment] 2023-12-29 16:28
This will probably be fixed by #2113

**Comment by frebib** [comment] 2024-01-02 17:51
Unfortunately #2113 does not fix this

**Comment by jmartinesp** [comment] 2024-01-04 13:04
> Unfortunately #2113 does not fix this

Are you sure? I can't reproduce this anymore.

**Comment by bmarty** [comment] 2024-01-04 13:49
I think it's due to the `"formatted_body":"\u003cp\u003ea\u003c/p\u003e\n"`, that I had not seen at first read.

**Comment by frebib** [comment] 2024-01-04 14:20
Yeah you could argue it's actually correct behaviour and maubot echo is at fault for producing an invalid formatted body?
```
{
  "type": "m.room.message",
  "sender": "@echo:nerdhouse.io",
  "content": {
    "msgtype": "m.notice",
    "body": "✨",
    "format": "org.matrix.custom.html",
    "formatted_body": "<p>✨</p>\n"
  },
  "origin_server_ts": 1704377737269,
  "unsigned": {
    "age": 93
  },
  "event_id": "$n8KLSPGdKjk0Ka4JHGGAdUyO3O8zLsTNzVF9G0CH0tw",
  "room_id": "!ping-v11:maunium.net"
}
```

Most other clients I've used seem to strip the trailing whitespace from these messages.
I don't see any such mentions of how clients are expected to handle this edge-case in the spec with a quick grep

**Comment by tulir** [comment] 2024-01-04 14:26
Newlines in HTML shouldn't be rendered at all (even in the middle of a message), except inside `<pre>` tags. Whitespace in general is mostly ignored, usually only single spaces between words are rendered, almost everything else must be dropped to have accurate rendering. https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace

**Comment by frebib** [comment] 2024-01-04 14:29
On that basis this sounds like a HTML parsing bug? It's probably also the culprit for (mis?)-interpreting the maubot `github` plugin messages.
This is how Ele-(Web|Desktop) renders them:
![badaebe](https://github.com/element-hq/element-x-android/assets/775104/d934ae99-ea55-4c6a-897a-c52e754a1cd4)

and how Element-X renders them
![Screenshot_20240104-142546](https://github.com/element-hq/element-x-android/assets/775104/097b8b8d-82ed-4ad4-8001-ee51a38a3dcc)

with the event being
```json
{
  "content": {
    "body": "**[mautrix/signal]** zmbcgn commented on [issue #232](https://github.com/mautrix/signal/issues/232): Check that room is still usable in `pm` command: \n> The problem also persists in the go rewrite: mautrix-signal 0.4.99+dev.717e58cb\n> \n> thanks to craeckie for the guide.",
    "com.beeper.linkpreviews": [],
    "format": "org.matrix.custom.html",
    "formatted_body": "<strong>[<a data-mautrix-exclude-plaintext href=\"https://github.com/mautrix/signal\">mautrix/signal</a>]</strong> <a data-mautrix-exclude-plaintext href=\"https://github.com/zmbcgn\">zmbcgn</a>     <a data-mautrix-exclude-plaintext href=\"https://github.com/mautrix/signal/issues/232#issuecomment-1877139385\">commented</a> on <a href=\"https://github.com/mautrix/signal/issues/232\">\n        issue\n        #232</a>: Check that room is still usable in `pm` command:\n    <blockquote><p>The problem also persists in the go rewrite: mautrix-signal 0.4.99+dev.717e58cb</p>\n<p>thanks to craeckie for the guide.</p>\n</blockquote>\n",
    "msgtype": "m.notice",
    "xyz.maubot.github.webhook": {
      "action": "created",
      "comment": {
        "id": 1877139385,
        "node_id": "IC_kwDOEc0jWc5v4t-5"
      },
      "delivery_ids": [
        "8e7df9a0-ab09-11ee-9330-e4c4f4e5321c"
      ],
      "event_type": "issue_comment",
      "issue": {
        "id": 1167348931,
        "node_id": "I_kwDOEc0jWc5FlFTD",
        "number": 232
      },
      "repository": {
        "id": 298656601,
        "name": "mautrix/signal",
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTg2NTY2MDE="
      }
    }
  },
  "origin_server_ts": 1704376804939,
  "sender": "@github:maunium.net",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$h40UYlmWEJ1H5nrjYEvbkSYddGSwANGONCK5w_5yF1k",
  "room_id": "!mautrix-signal-v6:maunium.net"
}
```

**Comment by jmartinesp** [comment] 2024-01-04 16:15
> This is probably also the culprit for (mis?)-interpreting the maubot github plugin messages.

Yes, it definitely looks like the same bug.

> Someone should probably invent a rust-sdk module that parses HTML correctly and converts it to an intermediate representation that's easy to render on Android and iOS 🤔

We actually wanted to do something like this, but sadly it never came up as a priority.

**Closed** 2024-01-05 11:40 UTC
Labels: S-Tolerable, T-Defect, O-Uncommon, A-Timeline, A-Event Rendering
