### ISSUE TITLE
Message text written with AnySoftKeyboard is entered incorrectly

### ISSUE THREAD

**Issue by returntrip** [element-hq/element-x-android#2636] opened 2024-04-02 07:53 UTC
### Steps to reproduce

Just to write some text using AnySoftKeyboard Canary. The first word will be written correctly Ann other words will be mispelled.attaching video to demonstrate the isssue.

https://github.com/element-hq/element-x-android/assets/14056122/93a97576-8515-4aec-9024-d8a650890cbb

#### What did you expect?
Test would be written correctly

#### What happened instead?
Only the first word is written correctly. The rest is gibberish.

### Your phone model

Samsung S22+

### Operating system version

Android 14

### Application version and app store

0.4.7

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment] 2024-04-02 14:04
It's a duplicate of https://github.com/element-hq/element-x-android/issues/2092

**Closed by jmartinesp** 2024-04-02 14:04 UTC
Labels: T-Defect

**Comment by fbruetting** [comment] 2024-04-03 03:16
No, this is a new misbehavior, introduced in v0.4.7.

When I tap every letter, it works fine. But as soon as I use swipe gestures, every word gets entered double without spaces. So usually swiping `xyz` and `abc` leads to `xyz abc` – whereas since yesterday, that action produces `xyzxyzabc`.
