### ISSUE TITLE
Pressing Back Button in Room/DM Does Not Return to Room List

### ISSUE THREAD

**Issue by atomdmac** [element-hq/element-x-android#3499] opened 2024-09-19 15:22 UTC
### Steps to reproduce

1. Receive a message notification from Room A.  Minimize the app.
2. Receive a message notification from Room B.  Minimize the app.
3. Receive a message notification from Room C.
4. Use the Android back button.

#### What did you expect?
To be returned to the Room list.

#### What happened instead?
1. Hit back 1 time = Returned to Room B
2. Hit back again = Returned to Room A
3. Hit back again = Returned to room list.

### Your phone model

Pixel 6

### Operating system version

14

### Application version and app store

0.6.2, Google Play

### Homeserver

Homeserver, Synapse with separate sliding sync server.

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by frebib** [comment] 2024-09-19 17:11
Duplicate of #3098

**Closed** 2024-09-30 07:55 UTC
Labels: T-Defect
