### ISSUE TITLE
Resent messages out of order after coming back online

### ISSUE THREAD

**Issue by kittykat** [element-hq/element-x-android#1881] opened 2023-11-24 10:49 UTC
### Steps to reproduce

1. Switch on airplane mode
2. Go to my test room (created as a room, converted to DM, I am only member)
3. Send (2) message(s) - I was intending to test sequence
4. Switch off airplane mode
5. Watch both messages move up in the timeline to be above older messages

#### What did you expect?
Unsent messages stay on the bottom

#### What happened instead?
Unsent messages to higher in the timeline than older messages (which were successfully received before the unsent messages are written)

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by delroth** [comment] 2024-01-21 00:43
FWIW I had this happen today (which happens to be the first day I try Element X / Sliding Sync on my account/homesever). I didn't go into airplane mode, the phone's deep sleep was enough to trigger the bug.

All my rooms are stuck with the last message (according to the timeline and the rooms list) being some hours ago, and all new messages are being inserted above some other old messages in the timeline.

Happy to try and provide logs if you can tell me what would be useful.

**Comment by bmarty** [comment] 2024-03-29 15:34
I can repro the problem with the latest Element X Android nightly.

Moreover, after the network is back, if I click on the second message and retry to sent it, it is sent but the first unsent message move again in the history of the timeline.

The message ordering is managed by the Rust SDK, I move the issue over there.

Note: I have checked and the issue is also observed on Element X iOS.

**Comment by bmarty** [comment] 2024-03-29 15:39
Replaced by https://github.com/matrix-org/matrix-rust-sdk/issues/3287

**Comment by manuroe** [comment] 2024-06-26 15:05
The SDK issue is now fixed. Let's close the app one.

**Closed by manuroe** 2024-06-26 15:05 UTC
Labels: S-Major, T-Defect, O-Occasional, A-Timeline, X-Needs-Rust, A-Offline
