### ISSUE TITLE
Remove mobile push notifications once a message is read on any client

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#1588] opened 2023-10-17 08:43 UTC
#### What would you like to do?
Once a message has been read on any Matrix client, its push notifications on EX should be removed.

#### Why would you like to do it?
There is no need for the push anymore, it turns into noise and hides unread messages.

#### How would you like to achieve it?
Call `cancel()` on the notification ID as described here: https://developer.android.com/develop/ui/views/notifications/build-notification#Removing

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment] 2023-10-19 12:40
Duplicate of element-meta/issues/1096

**Comment by toger5** [comment] 2024-10-30 15:55
As mentioned in this comment: https://github.com/element-hq/element-meta/issues/1096#issuecomment-1770936419
this issue is not exactly the same.
 - https://github.com/element-hq/element-meta/issues/1096 tries to mitigate sending the push notification all together when a room is actively viewed.
 - This issue here wants to cancel local push notifications once the user receives a read receipt update that implies that the notification is no longer unread.

**Comment by toger5** [comment] 2024-11-26 13:54
Thanks for tagging the duplicate. I did not find it when reopening this.

**Closed by toger5** 2024-11-26 13:54 UTC
Labels: T-Enhancement
