### ISSUE TITLE
Undecryptable messages after restoring backup

### ISSUE THREAD

**Issue by Aquathing** [element-hq/element-x-android#3382] opened 2024-09-02 20:18 UTC
### Steps to reproduce

- Uninstalled Element X
- Installed Element X 
- Restored backup immediately after login
- Messages sent by a user from a specific device are not decryptable

#### What did you expect?
Element X correctly decrypting the messages

#### What happened instead?
Element X unable to decrypt for "unknown" reasons.

Element Web was able to decrypt after a fresh login.

### Your phone model

Pixel 8

### Operating system version

GrapheneOS

### Application version and app store

Element X 0.5.1 40005012 APK GitHub

### Homeserver

Synapse v1.114

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by poljar** [comment] 2024-09-09 17:55
This might be the same as https://github.com/element-hq/element-x-ios/issues/3055 which was fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/3964. I'll leave this open as well until there's a EX-Android release confirming this.

**Comment by xundeenergie** [comment] 2024-09-10 21:16
Same here with 0.5.3 ex android.

It took hours, then messages got decrypted.

**Comment by Aquathing** [comment] 2024-10-01 12:55
I see this has been fixed on the SDK. Should this be closed?

**Comment by poljar** [comment] 2024-10-01 13:02
I think people leave the app issue open until a release happened with the updated SDK.

**Comment by richvdh** [comment] 2024-12-18 09:41
seems like a duplicate of https://github.com/element-hq/element-x-android/issues/3234

**Closed by richvdh** 2024-12-18 09:41 UTC
Labels: T-Defect
