### ISSUE TITLE
unable to mark a room as favorite

### ISSUE THREAD

**Issue by johansmitsnl** [element-hq/element-x-android#3495] opened 2024-09-19 01:11 UTC
### Steps to reproduce

1. Long press on the room
2. Check the toggle button

Or

1. Enter the room
2. Tab the name of the room
3. Try to toggle the favourite

#### What did you expect?

That it is marked as favorite

#### What happened instead?

Nothing

### Your phone model

Nokia XR20

### Operating system version

13

### Application version and app store

0.6.2

### Homeserver

synapse 0.115.0

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by davidegirardi** [comment] 2024-09-23 06:23
I also encountered this. I noticed that if you try to mark a room as favourite it actually works, you see a room become favourite in other clients like Element Desktop, but the change is not reflected in Element X Android.

Unmarking a room does not work since EXA believes the toggle is off already.

**Comment by networkException** [comment] 2024-09-23 20:32
I've been debugging this and it appears to be an issue in the `matrix-rust-sdk`. No `matrix_sdk_ffi::room_info::RoomInfo` that gets created in rust land has the `is_favourite` bit set, so changes to the value never reach the Kotlin side.

**Comment by networkException** [comment] 2024-09-24 17:55
It looks like there just was server side support for getting favorited rooms missing, as such this is likely a duplicate of #3521

**Comment by spaetz** [comment] 2024-09-26 05:47
This works well now with Synapse 1.116rc1 (perhaps already 1.115?) and EXA 0.6.4.

**Closed** 2024-09-26 07:35 UTC
Labels: T-Defect
