### ISSUE TITLE
Catasthrophic error, I can't even report error inside the app because of the immediate crashing.

### ISSUE THREAD

**Issue by thepragmaticmero** [element-hq/element-x-android#3121] opened 2024-07-01 18:52 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
I managed to login, but after logging app kept crashing every time I opened it. I can't even send crashing logs, crashes before I can press the "send" button
2. What do you click?
The app in my android app launcher
3. More steps…

### Outcome
Crash
#### What did you expect?
Non-crash
#### What happened instead?
Crash

### Your phone model

Redmi note 7

### Operating system version

ArrowOS 13.1 (Vanilla, no google apps)

### Application version and app store

Fdroid (Installed via Droid-ify)

### Homeserver

what

### Will you send logs?

I can't even do that

### Are you willing to provide a PR?

Idk about Kotlin lol I'm just here to say "use the webapp version"

**Comment by jmartinesp** [comment] 2024-07-02 05:56
Maybe a dupe of https://github.com/element-hq/element-x-android/issues/3086 ? It's difficult to say without logs (yeah, I know how ironic that is 😓 ).

**Comment by jmartinesp** [comment] 2024-07-02 06:00
At first I thought it was a dupe of some other issue, but I was wrong. Could you try adding logs using [adb logcat](https://developer.android.com/tools/logcat) or some app like [Catlog](https://github.com/nolanlawson/Catlog) so we can check what causes the crash, please?

**Comment by thepragmaticmero** [comment] 2024-07-02 14:57
Filtered by error:
`adb logcat -d "*:E" | grep io.element.android.x`
```
07-02 09:51:23.139 25223 25223 E AndroidRuntime: Process: io.element.android.x, PID: 25223
07-02 09:51:23.139 25223 25223 E AndroidRuntime: 	at io.element.android.x.intent.DefaultIntentProvider_Factory.get(SourceFile:425)
```
Unfiltered logcat output: 
`$ adb logcat -d | grep io.element.android.x`
```
07-02 09:51:18.432  3349  7447 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.element.android.x/.MainActivity bnds=[435,756][644,1015]} from uid 10132
07-02 09:51:18.459  3349  3381 I ActivityManager: Start proc 25223:io.element.android.x/u0a184 for next-top-activity {io.element.android.x/io.element.android.x.MainActivity}
07-02 09:51:18.461  3349  7447 D CoreBackPreview: Window{57fde6a u0 Splash Screen io.element.android.x}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@b8440d1, mPriority=0}
07-02 09:51:18.531 25223 25223 V GraphicsEnvironment: ANGLE Developer option for 'io.element.android.x' set to: 'default'
07-02 09:51:18.531 25223 25223 V GraphicsEnvironment: ANGLE GameManagerService for io.element.android.x: false
07-02 09:51:18.847  3349  3974 D CoreBackPreview: Window{32772c3 u0 io.element.android.x/io.element.android.x.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@f797679, mPriority=0}
07-02 09:51:18.930  3349  3370 I ActivityTaskManager: Displayed io.element.android.x/.MainActivity: +495ms
07-02 09:51:18.951  3349  3974 D CoreBackPreview: Window{57fde6a u0 Splash Screen io.element.android.x EXITING}: Setting back callback null
07-02 09:51:18.951  3349  7447 W InputManager-JNI: Input channel object '57fde6a Splash Screen io.element.android.x (client)' was disposed without first being removed with the input manager!
07-02 09:51:18.983  3349  3974 D ConnectivityService: requestNetwork for uid/pid:10184/25223 activeRequest: null callbackRequest: 1671 [NetworkRequest [ REQUEST id=1672, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
07-02 09:51:18.968 25223 25223 W pool-2-thread-1: type=1400 audit(0.0:4045): avc: denied { read } for name="version" dev="proc" ino=4026532111 scontext=u:r:untrusted_app:s0:c184,c256,c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=io.element.android.x
07-02 09:51:18.985  3349  3452 D WifiNetworkFactory: got request NetworkRequest [ REQUEST id=1672, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:18.985  3349  3452 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1672, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:18.985  3349  3452 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1672, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:18.985  3349  3452 D MultiInternetWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1672, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:18.987  3349  3974 D ConnectivityService: requestNetwork for uid/pid:10184/25223 activeRequest: null callbackRequest: 1673 [NetworkRequest [ REQUEST id=1674, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
07-02 09:51:18.988  3349  3452 D WifiNetworkFactory: got request NetworkRequest [ REQUEST id=1674, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:18.988  3349  3452 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1674, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:18.988  3349  3452 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1674, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:18.989  3349  3452 D MultiInternetWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1674, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:19.087  3349  7447 D ConnectivityService: requestNetwork for uid/pid:10184/25223 activeRequest: null callbackRequest: 1675 [NetworkRequest [ REQUEST id=1676, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
07-02 09:51:19.089  3349  3452 D WifiNetworkFactory: got request NetworkRequest [ REQUEST id=1676, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:19.089  3349  3452 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1676, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:19.089  3349  3452 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1676, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:19.089  3349  3452 D MultiInternetWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1676, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]
07-02 09:51:19.107  3349 19563 D CoreBackPreview: Window{af0b51e u0 io.element.android.x/io.element.android.x.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@39478b8, mPriority=0}
07-02 09:51:20.409  3349  3974 D CoreBackPreview: Window{af0b51e u0 io.element.android.x/io.element.android.x.MainActivity}: Setting back callback null
07-02 09:51:20.418  3349  3974 W InputManager-JNI: Input channel object 'af0b51e io.element.android.x/io.element.android.x.MainActivity (client)' was disposed without first being removed with the input manager!
07-02 09:51:23.139 25223 25223 E AndroidRuntime: Process: io.element.android.x, PID: 25223
07-02 09:51:23.139 25223 25223 E AndroidRuntime: 	at io.element.android.x.intent.DefaultIntentProvider_Factory.get(SourceFile:425)
07-02 09:51:23.147  3349  3974 W ActivityTaskManager:   Force finishing activity io.element.android.x/.MainActivity
07-02 09:51:23.198  3349  9327 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10184/25223, [NetworkRequest [ REQUEST id=1676, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]], android.os.BinderProxy@7842da9)
07-02 09:51:23.198  3349  3368 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10184/25223, [NetworkRequest [ LISTEN id=1677, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&FOREGROUND&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]], android.os.BinderProxy@37c7acf)
07-02 09:51:23.199  3349  3460 D ConnectivityService: releasing NetworkRequest [ REQUEST id=1676, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ] (release request)
07-02 09:51:23.199  3349 21731 I ActivityManager: Process io.element.android.x (pid 25223) has died: fg  TOP 
07-02 09:51:23.205  3349  7445 I WindowManager: WIN DEATH: Window{32772c3 u0 io.element.android.x/io.element.android.x.MainActivity}
07-02 09:51:23.205  3349  7446 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10184/25223, [NetworkRequest [ REQUEST id=1672, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]], android.os.BinderProxy@8c8fb65)
07-02 09:51:23.205  3349  7445 W InputManager-JNI: Input channel object '32772c3 io.element.android.x/io.element.android.x.MainActivity (client)' was disposed without first being removed with the input manager!
07-02 09:51:23.205  3349  3460 D ConnectivityService: releasing NetworkRequest [ REQUEST id=1672, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ] (release request)
07-02 09:51:23.208  3349 19563 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10184/25223, [NetworkRequest [ REQUEST id=1674, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ]], android.os.BinderProxy@2e71f2e)
07-02 09:51:23.208  3349  3460 D ConnectivityService: releasing NetworkRequest [ REQUEST id=1674, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10184 RequestorUid: 10184 RequestorPkg: io.element.android.x UnderlyingNetworks: Null] ] (release request)
07-02 09:51:23.244  3349  3374 W WindowManager: Failed to deliver inset state change to w=Window{32772c3 u0 io.element.android.x/io.element.android.x.MainActivity EXITING}
07-02 09:51:23.262  3349  3374 W WindowManager: Exception thrown during dispatchAppVisibility Window{32772c3 u0 io.element.android.x/io.element.android.x.MainActivity EXITING}
07-02 09:51:23.651  3349  3373 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{18a7a5e u0 io.element.android.x/.MainActivity} t-1 f}}
07-02 09:51:52.143 23255 23255 I AppLocaleUtil: Can display preference - [io.element.android.x] : isDisallowedPackage : false / isSignedWithPlatformKey : false / hasLauncherEntry : true / canDisplay : true
07-02 09:51:52.144 23255 23255 I AppLocaleUtil: Can display preference - [io.element.android.x] : isDisallowedPackage : false / isSignedWithPlatformKey : false / hasLauncherEntry : true / canDisplay : true
07-02 09:51:52.258 23255 23255 I AppLocaleUtil: Can display preference - [io.element.android.x] : isDisallowedPackage : false / isSignedWithPlatformKey : false / hasLauncherEntry : true / canDisplay : true
07-02 09:51:52.260  3349 28847 W PackageConfigPersister: App-specific configuration not found for packageName: io.element.android.x and userId: 0
07-02 09:51:52.302  3349  3534 W PackageConfigPersister: App-specific configuration not found for packageName: io.element.android.x and userId: 0
07-02 09:51:52.382  3349  3534 W PackageConfigPersister: App-specific configuration not found for packageName: io.element.android.x and userId: 0
07-02 09:51:52.436 15420 23375 I Role    : io.element.android.x not qualified for android.app.role.HOME due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.MAIN', mCategories='[android.intent.category.HOME]', mDataScheme='null', mDataType='null'}, mMinTargetSdkVersion=1, mPermission='null', mQueryFlags=0, mMetaData=[]}
07-02 09:51:52.438 15420 23375 I Role    : io.element.android.x not qualified for android.app.role.DIALER due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.DIAL', mCategories='[]', mDataScheme='null', mDataType='null'}, mMinTargetSdkVersion=1, mPermission='null', mQueryFlags=0, mMetaData=[]}
07-02 09:51:52.440 15420 23375 I Role    : io.element.android.x not qualified for android.app.role.SMS due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.provider.Telephony.SMS_DELIVER', mCategories='[]', mDataScheme='null', mDataType='null'}, mMinTargetSdkVersion=1, mPermission='android.permission.BROADCAST_SMS', mQueryFlags=0, mMetaData=[]}
```

This is my first time using `logcat` please don't bully me nagatoro

**Comment by jmartinesp** [comment] 2024-07-02 15:11
Thanks, although the stacktrace you added has most of its info filtered out by the `grep` usage it was enough to find the crash in Sentry:

```
java.lang.SecurityException: Settings key: <ringtone2> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
    at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:3080)
    at android.provider.Settings$System.getStringForUser(Settings.java:3770)
    at android.media.RingtoneManager.getActualDefaultRingtoneUriBySlot(RingtoneManager.java:827)
    at android.media.RingtoneManager.getActualDefaultRingtoneUri(RingtoneManager.java:805)
    at io.element.android.libraries.push.impl.notifications.channels.DefaultNotificationChannels.<init>(SourceFile:280)
    at io.element.android.appnav.intent.IntentResolver_Factory.get(SourceFile:207)
    at dagger.internal.DoubleCheck.get(SourceFile:14)
    at io.element.android.libraries.matrix.impl.RustMatrixClientFactory_Factory.get(SourceFile:22)
    at io.element.android.features.poll.impl.history.PollHistoryPresenter_Factory.get(SourceFile:8)
    at io.element.android.x.intent.DefaultIntentProvider_Factory.get(SourceFile:425)
    at io.element.android.features.ftue.impl.state.DefaultFtueService_Factory.get(SourceFile:22)
    at dagger.internal.DoubleCheck.get(SourceFile:14)
    at io.element.android.appnav.intent.IntentResolver_Factory.get(SourceFile:1156)
    at io.element.android.features.roomlist.impl.RoomListPresenter_Factory.get(SourceFile:151)
    at io.element.android.features.share.impl.ShareNode_AssistedFactory_Impl.create(SourceFile:422)
    at io.element.android.appnav.LoggedInFlowNode.resolve(SourceFile:171)
    at androidx.appcompat.widget.AppCompatBackgroundHelper.childEntry(SourceFile:23)
    at com.bumble.appyx.core.children.ChildAwareImpl$observeChanges$3.emit(SourceFile:199)
    at kotlinx.coroutines.flow.StateFlowImpl.collect(SourceFile:174)
    at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
    at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
    at kotlinx.coroutines.EventLoopImplPlatform.processUnconfinedEvent(SourceFile:24)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:84)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:33)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
    at kotlinx.coroutines.flow.StateFlowImpl.updateState(SourceFile:100)
    at kotlinx.coroutines.flow.StateFlowImpl.setValue(SourceFile:6)
    at io.element.android.features.ftue.impl.state.DefaultFtueService.updateState$impl_release(SourceFile:82)
    at io.element.android.features.ftue.impl.state.DefaultFtueService$updateState$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
    at kotlinx.coroutines.DispatchedTask.run(SourceFile:105)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7927)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

It seems like it's related to us trying to get the current ringtone to use it for Element Call ringing calls too, it's probably restricted in some OS versions (a custom ROM?). It looks easy enough to fix though!

> This is my first time using logcat please don't bully me nagatoro

<details>
<summary>Details</summary>

<img src="https://github.com/element-hq/element-x-android/assets/480955/a9a078d0-b137-4851-9137-543406aa2c3b" />

Had to 😄 .
</details>

**Comment by jmartinesp** [comment] 2024-07-02 15:57
By the way, just to double check: could you install the APK generated [here](https://github.com/element-hq/element-x-android/pull/3131#issuecomment-2203622659) and check the app doesn't crash anymore? I'm fairly sure those changes fixed the issue, but I have no way to test it myself.

The app will be quite slow since that's a debug version btw, it's not meant to be used as a daily driver.

**Closed** 2024-07-02 16:12 UTC
Labels: S-Critical, T-Defect, O-Uncommon, z-Crash

**Comment by thepragmaticmero** [comment] 2024-07-03 15:36
my mommy said to not install .apks from strangers, but Imma doit anyway for the good of opensauce

**Comment by thepragmaticmero** [comment] 2024-07-03 16:18
It works :D ~ tnks fellow contributor. If anyone is having a problem [here's the solution](https://github.com/element-hq/element-x-android/pull/3131#issuecomment-2203622659) until the fix becomes upstream.

Open source makes the best quality apps.
![Screenshot_20240703-110923](https://github.com/element-hq/element-x-android/assets/169491353/42afe859-c94b-4032-b64a-52657ee0dc8c)
