### ISSUE TITLE
Empty lines are removed when displaying messages

### ISSUE THREAD

**Issue by Massedil** [element-hq/element-x-android#3929] opened 2024-11-22 16:12 UTC
### Steps to reproduce

Send :

```
A

B
```

#### What did you expect?

You see : 

```
A

B
```

#### What happened instead?

You see : 

```
A
B
```

# Screenshot

1. On https://app.element.io

![1](https://github.com/user-attachments/assets/93793535-8435-45dd-ba91-415ef8b19271)

2. On Element X

![2](https://github.com/user-attachments/assets/0c9856f2-c7c1-48e4-a1ce-ab4fdf340fa8)

### Your phone model

Samsung Galaxy A52S 5G

### Operating system version

Android 14

### Application version and app store

Element X 0.7.3 (F-Droid)

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by frebib** [comment] 2024-11-22 20:48
Duplicate of #3001

**Closed** 2024-11-23 03:08 UTC
Labels: T-Defect
