### ISSUE TITLE
Android Conversations API

### ISSUE THREAD

**Issue by cyrneko** [element-hq/element-x-android#2992] opened 2024-06-07 02:57 UTC
#### What would you like to do?

(have someone) Implement the Android Conversations API

#### Why would you like to do it?

All kinds of improvements to notifications, like:

- set contact/room as having priority notifications
- show element x notifications at the top of the QS
- lay groundwork for Bubbles support
- allow usage of conversation shortcuts
- allow using Android built-in conversations widget(s)

#### How would you like to achieve it?

very nicely ask for it 👉👈

### Have you considered any alternatives?

other than using another client which implements the API, no.

### Additional context

N/A

### Are you willing to provide a PR?

No

**Comment by Xiretza** [comment] 2024-06-09 16:05
Possibly a dupe of #1547?

**Comment by ara4n** [comment] 2024-11-03 20:21
ypu, looks like a dup of #1547.

**Closed by ara4n** 2024-11-03 20:21 UTC
Labels: T-Enhancement
