### ISSUE TITLE
Creating several rooms results in a room preview being displayed

### ISSUE THREAD

**Issue by jmartinesp** [element-hq/element-x-android#3183] opened 2024-07-12 09:30 UTC
### Steps to reproduce

1. From the room list, create a new room, you should be taken into it immediately.
2. Go back to the room list.
3. Now create another room.
4. Instead of opening the new room, you'll see the room preview of the just created room instead.
5. If you go back to the room list, you won't be able to find the room in the list either until the app is restarted.

#### What did you expect?

The create room flow to be consistent.

#### What happened instead?

After the first room is created, the flow is broken.

### Your phone model

Xiaomi Mi 9

### Operating system version

Android 14

### Application version and app store

Element X Nightly (0.4.17)

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by manuroe** [comment] 2024-07-23 13:30
Status when testing on 2024-07-23 nightly: 
* New rooms appear at the top of list as expected 🥳 
* The room preview screen can still be displayed after the room creation 😢

**Comment by manuroe** [comment] 2024-07-24 08:50
@ganfra was not able to reproduce it on 0.4.16. The regression happened between 0.4.16 and 0.5.0.

**Comment by ganfra** [comment] 2024-07-24 12:10
Ok so after some digging, the steps are : 
- we create the room
- we waits for the room to appears in the RoomList
- we try to get a room from the associated `RoomListItem` => we got an exception from rust sdk 
`RoomListException$InitializingTimeline: error=Room `!DKIcUGPMMbrsaYEPYC:matrix.org` not found``
- It never recovers from that as we are expecting to have a full room at this point

**Comment by jmartinesp** [comment] 2024-08-06 10:02
I can't reproduce the issue anymore. @ganfra do you know a good way to make it easy to reproduce?

**Comment by manuroe** [comment] 2024-09-06 14:42
I tested it on the today nightly. The room preview screen appears every time I create a room on matrix.org, even for the first created room. I linked a rageshake to this issue in case it helps.

**Comment by manuroe** [comment] 2024-09-11 08:38
Project management trick: I moved this issue from the SSS project tasklist to the release blockers tasklist. Now, it is less related to SSS but more a global issue.

**Comment by jmartinesp** [comment] 2024-09-12 11:22
This should be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/3979 once we build a new SDK version.

**Comment by bmarty** [comment] 2024-09-16 14:50
Let's close the issue and open it again if it does not work as expected.

**Closed by bmarty** 2024-09-16 14:50 UTC
Labels: T-Defect, A-SSS
