### ISSUE TITLE
Chat history for members before they joined shows: Unable to decrypt - Unknown message inbox

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [element-hq/element-x-android#2226] opened 2024-01-13 09:52 UTC
### Steps to reproduce

1. Where are you starting? What can you see?
The title says everything
3. What do you click?

Basically after turned on end-to-end encryption (by default when someone makes an room in the app), my friend that is the owner there invited first it's staff team but after sending some messages for members there, and talked a little bit there the owner and me find out very soon that after each joining of an new member (starting from me), the member was unable to decrypt anything with another message that says that the member doesn't have the keys to decrypt it.

The owner tried to see can we turn off end-to-end encryption somehow and I find out very soon that it's impossible to disable it so I've told that to the owner and he tried to change chat history visibility to Anyone, after 2-3 days nothing happens - the older messages and posts there was never decrypted - they just changed the message status to (Unable to decrypt: Unknown message inbox)
5. More steps…
The issue is already explained with steps too

#### What did you expect?
I've expected that from the owner client app since the owner have those keys ti decrypt those messages, owner keys will be used by that client app to globally decrypt those messages (sent them to the server remotely) or to sent those keys remotely to each member that is invited and going to be invited to access fully the chat history in the target room. If that cannot be done, at least an feature in Element should be implemented sooner or later that will create an new menu for these encrypted message that is called (get keys remotely) and those keys should be requested from the owner client and from the moment the owner is online, the keys should be shared temporary to the server just to sent it to the another client (member) that should accept keys and keys will be automatically downloaded.

For easier method, this feature could work faster if the owner in it's chat history visibility choose an option (also part of wanted feature implementation) "Anyone (remotely)" and from that moment, owner keys for each message in the history would be uploaded safetly to the matrix server and every future encrypted messages will have those keys both in client (an app) and the server but no one will be able to locate nor use those keys from the server - only it can be used by clients in the rooms where the chat history visibility setting "Anyone (remotly)" is turned on by the owner itself for safety reasons.

#### What happened instead?
Just what the title says.

p.s This is both feature request and report in once

### Your phone model

Xiaomi Mi 11 Lite 5G NE (codename lisa)

### Operating system version

MIUI 14 based on Android 13 (Stock ROM by Xiaomi)

### Application version and app store

Official Element app from play store v1.6.10 and Element X app from play store 0.4.0

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by poljar** [comment] 2024-07-04 12:27
Since this claims that the invite happened before the messages I think those messages should have been decryptable.

I think that his is a duplicate of https://github.com/matrix-org/matrix-rust-sdk/issues/3529 which was fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/3533.

**Closed by poljar** 2024-07-04 12:27 UTC
Labels: S-Major, T-Enhancement, O-Occasional, A-E2EE
