### ISSUE TITLE
[Bug] Element X Doesn't Appear on Android Share Menu

### ISSUE THREAD

**Issue by 8227846265** [element-hq/element-x-android#2201] opened 2024-01-10 07:34 UTC
### Steps to reproduce

1. I take a screenshot from another app
2. I click "Share"
3. I look for Element X on the list of apps I can select to share the screenshot.
4. Element X doesn't appear as an option

#### What did you expect?
Element X is on the list of apps I can click on the Android Share Menu

#### What happened instead?
Element X is missing

### Your phone model

Xiaomi Poco F3

### Operating system version

MIUI Global 14.0.8 / Android 13

### Application version and app store

Element X version 0.4.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by rom4nik** [comment] 2024-01-10 08:07
Duplicate of #1980?

**Comment by bmarty** [comment] 2024-01-10 08:14
Yes, thanks.

**Closed by bmarty** 2024-01-10 08:14 UTC
Labels: T-Defect
