### ISSUE TITLE
Timestamp and edited text too close to short messages

### ISSUE THREAD

**Issue by bbhtt** [element-hq/element-x-android#1169] opened 2023-08-29 12:25 UTC
### Steps to reproduce

1. Send a short message like "test test"
2. See that the timestamp text almost overlaps it
3. Edit above message
4. See that part of the edited text now overlaps it

#### What did you expect?

Edit and timestamp should be properly spaced

#### What happened instead?

Too closely spaced

![image](https://github.com/vector-im/element-x-android/assets/62639087/ae06bf02-7139-43ca-b069-6f2ea03424ee)

### Your phone model

Nokia C3

### Operating system version

Android 10

### Application version and app store

0.1.5 (40001050)

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by anoadragon453** [comment] 2023-10-18 14:11
I can't reproduce this on my Google Pixel 4a 5G.

<details>

<summary>Click to see screenshot</summary>

![image](https://github.com/vector-im/element-x-android/assets/1342360/655f4fc2-edb6-4898-9ffc-5705b0fd0e0c)

</details>

**Comment by jmartinesp** [comment] 2024-01-04 12:11
This should be fixed by https://github.com/element-hq/element-x-android/pull/2113

**Closed by jmartinesp** 2024-01-04 12:11 UTC
Labels: S-Tolerable, T-Defect, O-Frequent, A-Timeline, Z-Schedule, Z-Polish
