### ISSUE TITLE
Replies include html in the content body 

### ISSUE THREAD

**Issue by spongythecake** [element-hq/element-x-android#2214] opened 2024-01-12 01:17 UTC
### Steps to reproduce

1. Join a room
2. Hold touch for context menu
3. Hit reply 
4. Compose msg and send 
 

#### What did you expect?

Body to be marked safe and formatted without html.

#### What happened instead?
View source on a message and notice html wrapped inside content body JSON. You see a hyperlink used with a msg.

> {"content":{"body":"<a data-mention-type=\"user\" href=\"https://matrix.to/#/@irc_\\Test_User|LC:matrix.f-hub.org\" contenteditable=\"false\">@\\Test_User|LC</a> I'm not doing anything different ","format":"org.matrix.custom.html","formatted_body":"<a href=\"https://matrix.to/#/@irc_\\Test_User|LC:matrix.f-hub.org\">@\\Test_User|LC</a> I'm not doing anything different\u00a0","m.mentions":{"user_ids":["@irc_\\Test_User|LC:matrix.f-hub.org"]},"msgtype":"m.text"},"origin_server_ts":1705008959957,"room_id":"!csFYqQwEzkhBXOMzLF:matrix.org","sender":"@spongycake:matrix.org","type":"m.room.message","unsigned":{"age":12205901,"transaction_id":"1841ec8cb1b04d5680e353c5ebb58161"},"event_id":"$osnpaDQmmdJX__StVEIn2-WRaYJLn0Bi_NmrWtVthTc","user_id":"@spongycake:matrix.org","age":12205901}

Adminis on a public room bridged to IRC are complaining to me that Element X is inserting html into replies. Element X's predecessor Element (Element Crazy Ex) handles messages differently, and does not insert HTML into replies.

### Room and bridges 

If you would like to see evidence of the interactions and full events, the room is publicly available. 

https://matrix.to/#/#libregaming-offtopic:tchncs.de

For bridged info:
[https://libregaming.org/chat-with-us/](https://libregaming.org/chat-with-us/)

The admin also had this to say about the matter: 

"Yes it's a client-side bug and doesn't appear to have been explicitly reported (you'll want to paste the View Source content), probably caused by the interaction between MSC3953 and PR#1850"

I can not comment on the substance of the admin's letter. However, I hope its useful. 

### Your phone model

Samsung Fold 5

### Operating system version

Android 14

### Application version and app store

Element X 0.4.0

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by giomfo** [comment] 2024-04-10 14:56
I tried to reproduce on my side. I would say that this is not an issue of the reply_to feature.

I succeeded to reproduce it by just mentioning a room member in a new message. Indeed EX-Android introduces unexpected html code in the event body when the user adds a pill in their message.
As soon as some html code has been introduced in the event body, any reply to this event includes html in its event body...

I don't reproduce this issue (html in event body) on EX-iOS

**Comment by spongythecake** [comment] 2024-04-20 07:36
I think the "@" mention is the source of the problem. A.k.a the pill

**Comment by jmartinesp** [comment] 2024-04-24 10:58
This seems to come from the Rich Text Editor library. For some reason, it's `EditorViewModel.getMarkdown()` function is returning this weird pseudo-HTML markdown instead of the actual markdown contents to send.

**Comment by jmartinesp** [comment] 2024-05-03 14:42
This should have been fixed now since the RTE library version that contains the fix was just merged in https://github.com/element-hq/element-x-android/pull/2791. Please reopen if you can still see the issue in the next nightly/stable release.

**Closed by jmartinesp** 2024-05-03 14:42 UTC
Labels: S-Major, T-Defect, O-Occasional, A-Rich-Text-Editor
