### ISSUE TITLE
URLs are not clickable in media captions

### ISSUE THREAD

**Issue by cyrneko** [element-hq/element-x-android#3850] opened 2024-11-10 21:22 UTC
### Steps to reproduce

1. Send a message with a media Captain
2. Make sure the caption contains a URL (https://...) somewhere
3. Observe issue

#### What did you expect?

URLs should be highlighted and clickable, as they are in normal text bodies

#### What happened instead?

The text is entirely plain, unclickable, without an underline nor is it blue 

### Your phone model

(Xiaomi) Poco F3

### Operating system version

Android 14

### Application version and app store

Element X 0.7.4 Nightly, b097e963

### Homeserver

bark.lgbt

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by frebib** [comment] 2024-11-10 22:23
Duplicate of #3529 (although this issue is better worded)

**Comment by cyrneko** [comment] 2024-11-11 10:00
> Duplicate of #3529 (although this issue is better worded)

oh I didn't catch that as I searched for "URL" not something like "link" :woozy_face:

**Closed** 2024-11-13 19:25 UTC
Labels: T-Defect
