### ISSUE TITLE
OIDC-authed client got spontaneously logged out.

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-android#2236] opened 2024-01-15 22:17 UTC
### Steps to reproduce

1. Open app
2. Discover you've been logged out

#### What did you expect?

No unexpected logouts.

#### What happened instead?

@kongo09 got unexpectedly logged out

### Your phone model

Pixel 5

### Application version and app store

0.4.2-nightly 

### Homeserver

element.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by kongo09** [comment] 2024-01-15 22:21
It happened after updating the Nightly.

And then happened again later over the day just out of the blue. The second time, I got the following screen with none of the items being true:

![Screenshot_20240115-182446](https://github.com/element-hq/element-x-android/assets/640121/ae02558f-6f1c-4922-b009-7d8fbba04ba8)

**Comment by spaetz** [comment] 2024-01-17 06:13
It did happen to me on synapse 1.98 yesterday with plain old password auth, no OIDC involved. Not sure if that is the deciding factor.

**Comment by jmartinesp** [comment] 2024-01-17 15:18
It happened to me several times today while testing on emulators. I've uploaded logs here: https://github.com/element-hq/element-x-android-rageshakes/issues/1355

**Comment by spaetz** [comment] 2024-01-18 11:19
Just becausr this has been tagged OIDC, the logouts happen in my synapse server with plain old password auth. No OIDC involved.

**Comment by spaetz** [comment] 2024-01-19 06:02
It happened again this morning (still on EXA 0.4.0), and I noticed that I was logged out of ALL of m sessions by synapse (Element Web claimed I had been logged out for security reasons). And when I logged in via EW, I only had one out of 4 sessions left.
Not sure if this is still caused by this issue or if it is some other issue (in EW or synapse).

**Comment by spaetz** [comment] 2024-01-21 07:45
Indeed, I keep getting logged out once a day with all my users despite not using EXA, so my issue is clearly not an EXA issue, please ignore my debug logs.

**Comment by jmartinesp** [comment] 2024-01-24 08:33
FWIW I haven't had any more unexpected logouts after https://github.com/element-hq/element-x-android/pull/2251. @kongo09, have you reproduced this issue again in the latest nightlies (since the end of last week)?

**Comment by bmarty** [comment] 2024-03-29 15:16
I think we can close the issue now. Feel free to re-open if necessary. Thanks @jmartinesp for the fix!

**Closed by bmarty** 2024-03-29 15:16 UTC
Labels: S-Critical, T-Defect, O-Occasional, A-Session Lifecycle

**Comment by manuroe** [comment] 2024-03-29 15:46
@VolkerJunginger is it an issue you see on EXA nightly?

**Comment by VolkerJunginger** [comment] 2024-04-02 07:24
Happens to me on iOS & Android nightly. Most of the time after updating the apps.
