### ISSUE TITLE
Element X is crashing at boot, no way to access anything.

### ISSUE THREAD

**Issue by GamePlayer-8** [element-hq/element-x-android#3462] opened 2024-09-15 11:16 UTC
### Steps to reproduce

1. Open Element X Android.
2. Use `https://catgirl.cloud` server for auth.
3. Recover account keys from the server or use authorization from another devices.
4. Crash after successfully authenticating.

Every boot up of the Element X leads into crash from now on.

#### What did you expect?

The application working.

#### What happened instead?

The application crashed.

### Your phone model

Samsung Galaxy A40

### Operating system version

Android 11

### Application version and app store

0.4.15

### Homeserver

catgirl.cloud

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment] 2024-09-16 14:30
Hello @GamePlayer-8 , is there any chance that you provide some log about the issue?

**Comment by GamePlayer-8** [comment] 2024-09-17 17:06
https://github.com/user-attachments/assets/c1b66604-71b6-4dff-8a19-54f4dcab0677

**Comment by GamePlayer-8** [comment] 2024-09-17 19:48
I've captured the log of the app in `adb logcat`: [android_elementx.log.txt](https://github.com/user-attachments/files/17034166/android_elementx.log.txt)

**Comment by bmarty** [comment] 2024-09-17 21:48
OK, thanks for the log.

The issue is maybe the same than https://github.com/element-hq/element-x-android/issues/3121, which has been fixed in 0.4.16.

Can you install a newer version?

**Comment by GamePlayer-8** [comment] 2024-09-18 09:37
I've realized, the latest version is `0.6.2` what has fixed the issue. Although F-Droid is still hosting `0.4.15` version in the repositories.

**Closed** 2024-09-24 12:43 UTC
Labels: T-Defect
